version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskManager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./taskManager.sql:/docker-entrypoint-initdb.d/taskManager.sql
    networks:
      - app-network

  app:
    build: .
    container_name: task-manager
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
